version: '3.3'

services:
  database:
    build:
      context: .
      dockerfile: ./docker/timescaledb/Dockerfile
    container_name: wmo-im-opencdms-database
    ports:
      - 5432:5432
    env_file:
      - default.env
    volumes:
      - <path-to-data-on-host>:/local/data
      - wmo-im-postgres:/home/postgres

  opencdms-cli:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    container_name: wmo-im-opencdms-cli
    env_file:
      - default.env
    tty: true
    volumes:
      - <path-to-source-on-host>:/local/app

volumes:
  wmo-im-postgres: